//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory_Managment_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Shift
    {
        public int ID { get; set; }
        public int Employee_ID { get; set; }
        public int Shift_ID { get; set; }
    }
}
