//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory_Managment_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Start_time { get; set; }
        public int End_time { get; set; }
    }
}
