//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory_Managment_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Full_name { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
        public int Num_of_actions { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
